title: Prabhat Agarwal
url: "https://prabhat1081.github.io"
baseurl: "/"

markdown: kramdown

tracking_id: #

footer: no
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Resume"
   link: "Resume_Prabhat_Agarwal.pdf"
 - name: "Contact"
   link: "contact"

theme: jekyll-theme-slate